services:
  backend_api:
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./api:/app
      - ./gcp_lib:/app/gcp_lib
      - ./data-scraping:/app/data-scraping
      - ./models:/app/models
      - ./requirements.txt:/app/requirements.txt
      - ./.env:/app/.env
      - ./credentials.json:/app/credentials.json
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials.json
      - PORT=8080
